
version: 2

sources:
  - name: raw
    database: lewagon-485210
    schema: gz_raw_data
    description: "dataset de notre gz_raw_data"
    config:
     freshness:
      warn_after: {count: 90, period: day}
    tables: # <--- C'est ici que tout doit commencer
      - name: produit
        identifier: raw_gz_product
        description: liste des produits 
        columns:
          - name: products_id
            tests:
              - not_null
              - unique

      - name: vente
        identifier: raw_gz_sales
        config:
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 3, period: day}
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id

      - name: livraison
        identifier: raw_gz_ship
        description: table des expeditions
        columns: 
          - name: orders_id
            tests:
              - not_null
              - unique

models:
  - name: int_orders_margin
    description: "Agrégation de la marge au niveau de la commande (orders_id)"
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null
      - name: margin
        description: "Somme des marges de tous les produits de la commande"

  - name: int_orders_operational
    description: "Marge opérationnelle (marge - coûts logistiques)"
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null               
      - name: operational_margin

  - name: int_sales_margin
    description: "Calcul de la marge ligne à ligne"
    columns:
      - name: margin
      - name: purchase_cost